services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    expose:
      - "3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=${NODE_ENV}
      - URL=${URL}
      - PORT=${PORT}
      - COLLABORATION_URL=${COLLABORATION_URL}
      - CDN_URL=${CDN_URL}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY}
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_CONNECTION_POOL_MIN=${DATABASE_CONNECTION_POOL_MIN}
      - DATABASE_CONNECTION_POOL_MAX=${DATABASE_CONNECTION_POOL_MAX}
      - REDIS_URL=${REDIS_URL}
      - REDIS_COLLABORATION_URL=${REDIS_COLLABORATION_URL}
      - FILE_STORAGE=${FILE_STORAGE}
      - FILE_STORAGE_LOCAL_ROOT_DIR=${FILE_STORAGE_LOCAL_ROOT_DIR}
      - FILE_STORAGE_UPLOAD_MAX_SIZE=${FILE_STORAGE_UPLOAD_MAX_SIZE}
      - FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE=${FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE}
      - SSL_KEY=${SSL_KEY}
      - SSL_CERT=${SSL_CERT}
      - FORCE_HTTPS=${FORCE_HTTPS}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_SERVER_ID=${DISCORD_SERVER_ID}
      - DISCORD_SERVER_ROLES=${DISCORD_SERVER_ROLES}
      - OIDC_USERNAME_CLAIM=${OIDC_USERNAME_CLAIM}
      - OIDC_DISPLAY_NAME=${OIDC_DISPLAY_NAME}
      - OIDC_SCOPES=${OIDC_SCOPES}
      - RATE_LIMITER_ENABLED=${RATE_LIMITER_ENABLED}
      - RATE_LIMITER_REQUESTS=${RATE_LIMITER_REQUESTS}
      - RATE_LIMITER_DURATION_WINDOW=${RATE_LIMITER_DURATION_WINDOW}
      - ENABLE_UPDATES=${ENABLE_UPDATES}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}

  redis:
    image: redis
    expose:
      - "6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    environment:
      - NODE_ENV=${NODE_ENV}
      - URL=${URL}
      - PORT=${PORT}
      - COLLABORATION_URL=${COLLABORATION_URL}
      - CDN_URL=${CDN_URL}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY}
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_CONNECTION_POOL_MIN=${DATABASE_CONNECTION_POOL_MIN}
      - DATABASE_CONNECTION_POOL_MAX=${DATABASE_CONNECTION_POOL_MAX}
      - REDIS_URL=${REDIS_URL}
      - REDIS_COLLABORATION_URL=${REDIS_COLLABORATION_URL}
      - FILE_STORAGE=${FILE_STORAGE}
      - FILE_STORAGE_LOCAL_ROOT_DIR=${FILE_STORAGE_LOCAL_ROOT_DIR}
      - FILE_STORAGE_UPLOAD_MAX_SIZE=${FILE_STORAGE_UPLOAD_MAX_SIZE}
      - FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE=${FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE}
      - SSL_KEY=${SSL_KEY}
      - SSL_CERT=${SSL_CERT}
      - FORCE_HTTPS=${FORCE_HTTPS}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_SERVER_ID=${DISCORD_SERVER_ID}
      - DISCORD_SERVER_ROLES=${DISCORD_SERVER_ROLES}
      - OIDC_USERNAME_CLAIM=${OIDC_USERNAME_CLAIM}
      - OIDC_DISPLAY_NAME=${OIDC_DISPLAY_NAME}
      - OIDC_SCOPES=${OIDC_SCOPES}
      - RATE_LIMITER_ENABLED=${RATE_LIMITER_ENABLED}
      - RATE_LIMITER_REQUESTS=${RATE_LIMITER_REQUESTS}
      - RATE_LIMITER_DURATION_WINDOW=${RATE_LIMITER_DURATION_WINDOW}
      - ENABLE_UPDATES=${ENABLE_UPDATES}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}

  postgres:
    image: postgres:18
    expose:
      - "5432"
    volumes:
      - database-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "outline"

volumes:
  https-portal-data:
  storage-data:
  database-data:
